### ISSUE TITLE
int16 not defined with select * from

### ISSUE THREAD

**Issue by amoradell** [nakagami/Firebird.jl#1]
- Julia 1.6.3
- Windows 10
- Firebird 3 srp

I managed to connect to database

Also, a select with columns defined is ok, see below

`res = (DBInterface.execute(conn, "SELECT ORIGFILEROWNUMBER AS ID, IDENTIFIANT_PP, NOM_D_EXERCICE, PRENOM_D_EXERCICE FROM Z_PS202108 where ORIGFILEROWNUMBER between 500000 and 500010"))`

but when I use `select * from`, I got following error

```julia> res = (DBInterface.execute(conn, "SELECT * FROM Z_PS202108 where ORIGFILEROWNUMBER between 500000 and 500010"))
ERROR: UndefVarError: int16 not defined
Stacktrace:
 [1] parse_xsqlda(wp::Firebird.WireProtocol, buf::Vector{UInt8}, stmt_handle::Int32)
   @ Firebird C:\Users\amoradell\.julia\packages\Firebird\QDDO0\src\wireprotocol.jl:500
 [2] Firebird.Statement(conn::Firebird.Connection, sql::String)
   @ Firebird C:\Users\amoradell\.julia\packages\Firebird\QDDO0\src\statement.jl:52
 [3] prepare
   @ C:\Users\amoradell\.julia\packages\Firebird\QDDO0\src\statement.jl:66 [inlined]
 [4] execute(conn::Firebird.Connection, sql::String, params::Tuple{}) (repeats 2 times)
   @ Firebird C:\Users\amoradell\.julia\packages\Firebird\QDDO0\src\execute.jl:89
 [5] top-level scope```

**Comment by nakagami** [comment]
Please show me column data type

- ORIGFILEROWNUMBER
- IDENTIFIANT_PP
- NOM_D_EXERCICE
- PRENOM_D_EXERCICE

**Comment by amoradell** [comment]
```
ORIGFILEROWNUMBER bigint,
  ORIGFILENAME varchar(30),
  ORIGINSERTTIME timestamp,
  ORIGRANDGROUP bigint,

```

**Comment by amoradell** [comment]
Full DDL below

CREATE TABLE Z_PS202108
(
  ORIGFILEROWNUMBER bigint,
  ORIGFILENAME varchar(30),
  ORIGINSERTTIME timestamp,
  ORIGRANDGROUP bigint,
  TYPE_D_IDENTIFIANT_PP bigint,
  IDENTIFIANT_PP varchar(12),
  IDENTIFICATION_NATIONALE_PP varchar(13),
  CODE_CIVILITE_D_EXERCICE varchar(3),
  LIBELLE_CIVILITE_D_EXERCICE varchar(11),
  CODE_CIVILITE varchar(5),
  LIBELLE_CIVILITE varchar(13),
  NOM_D_EXERCICE varchar(50),
  PRENOM_D_EXERCICE varchar(28),
  CODE_PROFESSION bigint,
  LIBELLE_PROFESSION varchar(32),
  CODE_CATEGORIE_PROFESSIONNE varchar(2),
  LIBELLE_CATEGORIE_PROFESSIO varchar(10),
  CODE_TYPE_SAVOIR_FAIRE varchar(4),
  LIBELLE_TYPE_SAVOIR_FAIRE varchar(21),
  CODE_SAVOIR_FAIRE varchar(6),
  LIBELLE_SAVOIR_FAIRE varchar(61),
  CODE_MODE_EXERCICE varchar(2),
  LIBELLE_MODE_EXERCICE varchar(9),
  NUMERO_SIRET_SITE varchar(30),
  NUMERO_SIREN_SITE bigint,
  NUMERO_FINESS_SITE varchar(10),
  NUMERO_FINESS_ETABLISSEMENT varchar(10),
  IDENTIFIANT_TECHNIQUE_DE_LA varchar(19),
  RAISON_SOCIALE_SITE varchar(165),
  ENSEIGNE_COMMERCIALE_SITE varchar(51),
  COMPLEMENT_DESTINATAIRE_COO varchar(41),
  COMPLEMENT_POINT_GEOGRAPHIQ varchar(40),
  NUMERO_VOIE_COORD_STRUCTUR varchar(5),
  INDICE_REPETITION_VOIE_COOR varchar(4),
  CODE_TYPE_DE_VOIE_COORD_ST varchar(5),
  LIBELLE_TYPE_DE_VOIE_COORD varchar(29),
  LIBELLE_VOIE_COORD_STRUCTU varchar(39),
  MENTION_DISTRIBUTION_COORD varchar(40),
  BUREAU_CEDEX_COORD_STRUCTU varchar(39),
  CODE_POSTAL_COORD_STRUCTUR varchar(6),
  CODE_COMMUNE_COORD_STRUCTU varchar(6),
  LIBELLE_COMMUNE_COORD_STRU varchar(46),
  CODE_PAYS_COORD_STRUCTURE bigint,
  LIBELLE_PAYS_COORD_STRUCTU varchar(12),
  TELEPHONE_COORD_STRUCTURE varchar(16),
  TELEPHONE_2_COORD_STRUCTUR varchar(16),
  TELECOPIE_COORD_STRUCTURE varchar(16),
  ADRESSE_E_MAIL_COORD_STRUC varchar(61),
  CODE_DEPARTEMENT_STRUCTURE bigint,
  LIBELLE_DEPARTEMENT_STRUCTU bigint,
  ANCIEN_IDENTIFIANT_DE_LA_ST varchar(16),
  AUTORITE_D_ENREGISTREMENT varchar(22),
  CODE_SECTEUR_D_ACTIVITE varchar(5),
  LIBELLE_SECTEUR_D_ACTIVITE varchar(51),
  CODE_SECTION_TABLEAU_PHARMA varchar(3),
  LIBELLE_SECTION_TABLEAU_PHA varchar(234)
);

CREATE UNIQUE INDEX IDX_Z_PS2021081 ON Z_PS202108 (ORIGFILEROWNUMBER);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON Z_PS202108 TO  SYSDBA WITH GRANT OPTION;

**Comment by amoradell** [comment]
Same problem with a full select

```
julia> res = (DBInterface.execute(conn, "SELECT r.ORIGFILEROWNUMBER, r.ORIGFILENAME, r.ORIGINSERTTIME, r.ORIGRANDGROUP, r.TYPE_D_IDENTIFIANT_PP, r.IDENTIFIANT_PP, r.IDENTIFICATION_NATIONALE_PP, r.CODE_CIVILITE_D_EXERCICE, r.LIBELLE_CIVILITE_D_EXERCICE, r.CODE_CIVILITE, r.LIBELLE_CIVILITE, r.NOM_D_EXERCICE, r.PRENOM_D_EXERCICE, r.CODE_PROFESSION, r.LIBELLE_PROFESSION, r.CODE_CATEGORIE_PROFESSIONNE, r.LIBELLE_CATEGORIE_PROFESSIO, r.CODE_TYPE_SAVOIR_FAIRE, r.LIBELLE_TYPE_SAVOIR_FAIRE, r.CODE_SAVOIR_FAIRE, r.LIBELLE_SAVOIR_FAIRE, r.CODE_MODE_EXERCICE, r.LIBELLE_MODE_EXERCICE, r.NUMERO_SIRET_SITE, r.NUMERO_SIREN_SITE, r.NUMERO_FINESS_SITE, r.NUMERO_FINESS_ETABLISSEMENT, r.IDENTIFIANT_TECHNIQUE_DE_LA, r.RAISON_SOCIALE_SITE, r.ENSEIGNE_COMMERCIALE_SITE, r.COMPLEMENT_DESTINATAIRE_COO, r.COMPLEMENT_POINT_GEOGRAPHIQ, r.NUMERO_VOIE_COORD_STRUCTUR, r.INDICE_REPETITION_VOIE_COOR, r.CODE_TYPE_DE_VOIE_COORD_ST, r.LIBELLE_TYPE_DE_VOIE_COORD, r.LIBELLE_VOIE_COORD_STRUCTU, r.MENTION_DISTRIBUTION_COORD, r.BUREAU_CEDEX_COORD_STRUCTU, r.CODE_POSTAL_COORD_STRUCTUR, r.CODE_COMMUNE_COORD_STRUCTU, r.LIBELLE_COMMUNE_COORD_STRU, r.CODE_PAYS_COORD_STRUCTURE, r.LIBELLE_PAYS_COORD_STRUCTU, r.TELEPHONE_COORD_STRUCTURE, r.TELEPHONE_2_COORD_STRUCTUR, r.TELECOPIE_COORD_STRUCTURE, r.ADRESSE_E_MAIL_COORD_STRUC, r.CODE_DEPARTEMENT_STRUCTURE, r.LIBELLE_DEPARTEMENT_STRUCTU, r.ANCIEN_IDENTIFIANT_DE_LA_ST, r.AUTORITE_D_ENREGISTREMENT, r.CODE_SECTEUR_D_ACTIVITE, r.LIBELLE_SECTEUR_D_ACTIVITE, r.CODE_SECTION_TABLEAU_PHARMA, r.LIBELLE_SECTION_TABLEAU_PHA FROM Z_PS202108 r where r.ORIGFILEROWNUMBER between 500000 and 500010"))
ERROR: UndefVarError: int16 not defined
```

**Comment by nakagami** [comment]
thanks
I think it's fixed.

Can you try to get the master branch of this repository and test it?

**Comment by amoradell** [comment]
It works
Thanks !
