### ISSUE TITLE
When trying to read column with timestamp I get wrong date - bigger in one from the actual date

### ISSUE THREAD

**Issue by Roeya** [nakagami/Firebird.jl#3]
The table as date which is `2014-04-13T11:21:22 (I see it using Flamerobin tool) 
However when I try to read the stime stamp I get 2014-04-**14**T11:21:22 (notice the 14 instead of 13)
Sometimes this off by one date causes and error in reading the date

PS thank you for the Firebird modules in Go, Rust and now in Julia I use them all !

I use firebird 3 (3.0.10) there is no timezone

**Comment by nakagami** [comment]
Thank you.
I'm glad to hear both reports of it working properly and of glitches!

I was able to reproduce the phenomenon, so I have fixed it and released it as v0.2.4.

https://juliahub.com/ui/Packages/General/Firebird/0.2.4

**Comment by Roeya** [comment]
Thanks !
